### ISSUE TITLE
create German translation

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/rmw#119]
@kickbutts , would you be interested in doing this?

Instructions for creating translations are at https://github.com/theimpossibleastronaut/rmw/wiki/Translating

This is the .pot file that needs translating:
https://github.com/theimpossibleastronaut/rmw/blob/master/po/rmw.pot

Translators are encouraged to join the [chat room](https://join.slack.com/t/removetowaste/shared_invite/enQtMjU3NTA0NTI2OTgzLTkzMzQxNDhjYzlkM2UxMTA2MzJjNWYyZjAyYzkyNWNmZjJmYWZmYjUyODk2NzNkNzBhMzFjOGZkMTg2MzAxMTM)

**Comment by pille1842** [comment]
I'll take it.
