### ISSUE TITLE
Create Portuguese Brasilian translation

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/rmw#120]
@alagoa or @localhostpedro, would you be interested in doing this?

Instructions for creating translations are at https://github.com/andy5995/rmw/wiki/Translating

This is the .pot file that needs translating:
https://github.com/andy5995/rmw/blob/master/po/rmw.pot

Translators are encouraged to join the [chat room](https://join.slack.com/t/removetowaste/shared_invite/enQtMjU3NTA0NTI2OTgzLTkzMzQxNDhjYzlkM2UxMTA2MzJjNWYyZjAyYzkyNWNmZjJmYWZmYjUyODk2NzNkNzBhMzFjOGZkMTg2MzAxMTM)

**Comment by jmrodriguesgoncalves** [comment]
I can try and help out with this!

**Comment by andy5995** [comment]
Great! Let me know if you have any questions. :)

**Comment by andy5995** [comment]
Thanks for completing the pt_PT translations @jmrodriguesgoncalves (4abcee933857a91536f44f75548e8388df8a3b32)

I'll leave this ticket open. Is anyone available for a pt_BR translation?

**Comment by andy5995** [comment]
@marioecg, would you be interested in translating the output messages? Instructions are at https://github.com/andy5995/rmw/wiki/Translating

**Comment by marioecg** [comment]
@andy5995 sure, I'll take a look at it.

**Comment by andy5995** [comment]
This was completed by @jmrodriguesgoncalves  in https://github.com/theimpossibleastronaut/rmw/commit/b77f2dba02168c0492ca2a9d8a5b7e7d57665c47

and I copied the file over in https://github.com/theimpossibleastronaut/rmw/commit/4abcee933857a91536f44f75548e8388df8a3b32#diff-20f31f46cccc84ba5c3fd23f6dd6a1d5
