### ISSUE TITLE
list of files in trash should be sorted

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/rmw#129]
This is a matter of sorting the "choices" array.

For each entry in "choices" there's a corresponding file size in the "desc" array, so they'll have to match up during the sort.

https://github.com/andy5995/rmw/blob/85f26be661e740fcc4bb61a9a2ebff35772cfc0f/src/functions/restore_rmw.c#L394-L402

**Comment by Ethan-ks** [comment]
I'd like to contribute, do you want it sorted alpabetically?

**Comment by andy5995** [comment]
Thank you for the offer. Yes, alphabetically.

**Comment by andy5995** [comment]
Hi @Ethan-ks , are you still working on this?

**Comment by andy5995** [comment]
I'll take this issue. Planning to implement my first [binary node tree](http://www.zentut.com/c-tutorial/c-binary-search-tree/)
