### ISSUE TITLE
Decrease the required gettext version to compile in OpenBSD

### ISSUE THREAD

**Issue by su8** [theimpossibleastronaut/rmw#154]

**Comment by su8** [comment]
In OpenBSD the shipped version is **0.19.7** while in the configure.ac it requires 0.19.**8**

**Comment by andy5995** [comment]
0.19.7 ships with OpenBSD 6.0, but 0.19.8.1 ships with [6.1](https://mirror.bytemark.co.uk/pub/OpenBSD/6.1/packages/amd64/) and 6.2

**Comment by andy5995** [comment]
Actually, the option to require a version is not enabled in configure.ac and never has been. To enforce a required version would require a different function

https://github.com/theimpossibleastronaut/rmw/blob/c7f794146340dd92a7c0472f4d088fd780cf6647/m4/gettext.m4#L415-L420

We're only using AM_GNU_GETTEXT_VERSION in configure.ac
