### ISSUE TITLE
check and clean orphaned .trashinfo files and regular files

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/rmw#16]
rewriting code and testing sometimes results in files that have no .trashinfo file associated with them, or vice versa. A feature that checks for this would be good for the long-term process of development, in case there are bugs that have been missed.

A routine that reads the .trashinfo is already in purge() and restore(), and file_not_found() checks for the existence of a file. It would have to be copied and altered a little to create a function that just checks for "orphans", and deletes them if the option is specified on the command line.

Something like 'rmw -o' would list them, and 'rmw -o cleanup' would erase them.

**Comment by andy5995** [comment]
This is how I thought of approaching this.

add -o --orphaned   "check for orphaned files"

1. When purge searches the .trashinfo's for files that meet the criteria for purging, and the date matches (time to purge that file), but the corresponding file in /files/ doesn't exist, simply remove the trashinfo. Print a message like "orphaned, removing <trashinfo>"

2. When -o is used, read each file in /files/ (routine can be adapted from the code near [L232](https://github.com/andy5995/rmw/blob/5c4b6c2bdd14ded3a86d0b0f1d5e5f7a3022f39c/src/functions/restore_rmw.c#L232). If it doesn't exist, create a trashinfo file for it. Because we don't know where the file came from, use Path=$HOME/rmw_orphan/<filename> so if it gets restored it will have a place to go.

Anybody else have ideas for this?

**Comment by ajphukan** [comment]
we can use the single command for the orphaned file showing and removing ...
Because there is no reason to put them ....in the info folder ..

**Comment by andy5995** [comment]
I'm not sure what you mean.

**Comment by andy5995** [comment]
There's already two functions that read the lines from a trashinfo, and this will make a third.

So first I'm going to write a single function that will parse a trashinfo, and it will be used by the other three.

**Comment by ajphukan** [comment]
in my above comment i am suggesting that there is no need to make separate function for orphan deletion . we can make a single function to delete the file first and then just notify the user which files are deleted .

**Comment by andy5995** [comment]
After giving it some thought, I decided a separate function would be the best in this case, but it will use other functions, such as mkinfo.

**Comment by andy5995** [comment]
https://github.com/andy5995/rmw/commit/94f60363be2e4118dbf460122a3311728539a964 Needs error checking upon opening and closing the dir, and a few other areas as well.

I also need to add to the function: If a trashinfo file exists, but no corresponding file, then remove the trashinfo.

**Comment by andy5995** [comment]
I don't see that anything else has to be done with this.
