### ISSUE TITLE
Add French translation

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/rmw#182]
Instructions for creating translations are at https://github.com/theimpossibleastronaut/rmw/wiki/Translating

This is the .pot file that needs translating:
https://github.com/theimpossibleastronaut/rmw/blob/master/po/rmw.pot

Translators are encouraged to join the [chat room](https://join.slack.com/t/removetowaste/shared_invite/enQtMjU3NTA0NTI2OTgzLTkzMzQxNDhjYzlkM2UxMTA2MzJjNWYyZjAyYzkyNWNmZjJmYWZmYjUyODk2NzNkNzBhMzFjOGZkMTg2MzAxMTM)

**Comment by vchellen** [comment]
ok i'll check

**Comment by vchellen** [comment]
Hello,

I've added the translation and created a pull request : https://github.com/theimpossibleastronaut/rmw/pull/185 could you please review and accept?

Thanks
