### ISSUE TITLE
On osx, required libs (libmenuw and ncursesw) can't be found

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/rmw#207]
Build fails, 
on osx, required libs (libmenu and ncursesw) can't be found

**Comment by andy5995** [comment]
@sexybiggetje , can you tell me what output you get when you run `pkg-config --libs ncursesw`

**Comment by sexybiggetje** [comment]
Sure!

> martijn$ pkg-config --libs ncursesw
> Package ncursesw was not found in the pkg-config search path.
> Perhaps you should add the directory containing `ncursesw.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'ncursesw' found

**Comment by andy5995** [comment]
ok, this is the output I get on mine when its found:

`-lncursesw -ltinfo`

What if you run `pkg-config --libs ncurses` (without the 'w' at the end)?

**Comment by sexybiggetje** [comment]
> pkg-config --libs ncurses
> Package ncurses was not found in the pkg-config search path.
> Perhaps you should add the directory containing `ncurses.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'ncurses' found

Not too satisfactory I presume?

**Comment by andy5995** [comment]
I found an m4 file provided by the GNU aclocal package. Made things a bit easier for testing.

I don't know why pkg-config can't find the files on OpenBSD or High Sierra. I looked on my OpenBSD machine for the .pc files for ncurses and menu but couldn't find them.

**Comment by andy5995** [comment]
The path to ncursesw.pc and menuw.pc can be manually specified. For example, although I already installed libncursesw with apt-get, I see it was also installed with brew:

    PKG_CONFIG_PATH=~/.linuxbrew/lib/pkgconfig ../configure

@sexybiggetje do you have those 2 pc files in your brew lib/pkgconfig directories?
