### ISSUE TITLE
purge function can be split into two or more functions

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/rmw#210]
https://github.com/theimpossibleastronaut/rmw/blob/7456e89d561e0d3467d74abade865ea29ab74ad0/src/purging_rmw.c#L159

This function is far longer than it needs to be. Best to chop it up.

If you want some ideas on the first step, let me know.

If you have ideas on how to split it, run them by me first.

Before trying to make 3 or 4 functions out of it, let's just do one a time, i.e. wait for the first one to get approved and merged, etc.

**Comment by dbugnar** [comment]
Hello, I had an idea and I split a bit the purge function. I opened a PR on this. If you have more ideas maybe I can continue working on this. 
Thanks.

**Comment by andy5995** [comment]
https://github.com/theimpossibleastronaut/rmw/commit/ad9dab60be506b3c10d59ba03bf6ec9412bb4fd4

@dbugnar Thanks for the offer. As I look it over now, after your changes, I don't really see a need for any more splitting.

There are probably some other excessively long functions though but I can't think of them right now. I'll let you know.
