### ISSUE TITLE
rmw is unable to use the system trash folder on a Mac

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/rmw#213]
I may need to do some work to have rmw be able to access the system (desktop) trash on a Mac. I confess I never gave it any thought before. People have told me it worked it on a Mac, but I'm not sure any Mac user ever tried it with their system trash.

@msiverts

In the [rmw chat room](https://riot.im/app/#/room/!XeJxcdkywroPaRKKtr:matrix.org), I've asked @sexybiggetje about using the system trash on a Mac. He's going to do some checking.

I found a little preliminary info by searching... Apparently your system trash is stored in ~/.Trash.

rmw creates ".trashinfo" files though, the same method the desktop trash on Linux uses. Is the layout of your Trash directory something like this?

~/.Trash
~/.Trash/files/ (where the files are stored)
~/.Trash/info/  (where the corresponding .trashinfo files are stored)

The format of a .trashinfo file looks like this:

[Trash Info]
Path=/home/andy/Downloads/bash-4.4.tar.gz
DeletionDate=2018-11-15T00:06:58

If the structure of your ~/.Trash doesn't match with the above description, you're still safe to use rmw, but **don't add your ~/.Trash folder to the config file.** You'll notice the default directory specified in the config file is ~/.trash.rmw.

As for the trash on different filesystems or removable devices, that's another matter. Right now, rmw can use any folder on any filesystem once it's created, but the goal is having it more "automatic" (see also #134).

**Comment by sexybiggetje** [comment]
I'm thinking that if there is any metadata at all it's attached to the files. Subfolders are trashed on emptying as well.

`kenpachi:andy martijn$ tree ~/.Trash/
/Users/martijn/.Trash/
└── test.txt

0 directories, 1 file`

**Comment by andy5995** [comment]
@sexybiggetje The metadata is apparently stored in a '.DS_Store' file

https://ponderthebits.com/2017/01/mac-dumpster-diving-identifying-deleted-file-references-in-the-trash-ds_store-files-part-1/

I doubt this ticket will ever be done. I know it won't be done by me, as I don't use a Mac. Closing...
