### ISSUE TITLE
./configure should fail if it can't find ncurses

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/rmw#221]
configure should fail if it can't find any usable curses required header or library

**Comment by Jammyjamjamman** [comment]
Andy managed to help me to get this to work.I think there's a slight mistake in the wording for the build instructions:

> Note: On **OpenBSD**, you must precede `./configure` with `MENU_LIBS=-lmenuw`.
> Example:
> 
>     MENU_LIBS=-lmenuw ./configure

This isn't only required for OpenBSD, but I think it's also true for most non-Debian-based Linux OS'es (or any linux os without the `ncursesw` libs).

**Comment by andy5995** [comment]
@Jammyjamjamman Could you try it with MENU_LIBS=-lmenuw and see if it still works? (w at the end)

**Comment by andy5995** [comment]
> Andy managed to help me to get this to work.I think there's a slight mistake in the wording for the build instructions:
> 
> > Note: On **OpenBSD**, you must precede `./configure` with `MENU_LIBS=-lmenuw`.
> > Example:
> > ```
> > MENU_LIBS=-lmenuw ./configure
> > ```
> 
> This isn't only required for OpenBSD, but I think it's also true for most non-Debian-based Linux OS'es (or any linux os without the `ncursesw` libs).

@Jammyjamjamman I've updated that https://github.com/theimpossibleastronaut/rmw#if-configure-fails

Also patched configure.ac so configure should fail now if menu isn't found. Could you give it a test sometime?

Thanks for your help troubleshooting yesterday and doc suggestions.
