### ISSUE TITLE
distributing releases as App Images

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/rmw#239]
With a small program like rmw, would there be any advantage to offering [App Images](https://appimage.org/)? And if so, would anyone be interested in maintaining it?

**Comment by Jammyjamjamman** [comment]
Because its so small and has not too many deps, I'd be more tempted to distribute a static-lib-build version instead... assuming that is possible.

**Comment by andy5995** [comment]
A static build can be done by doing `LDFLAGS=-static ../configure` before make.

I added an rpm package with a static build to the [0.7.02 release page](https://github.com/theimpossibleastronaut/rmw/releases/tag/v0.7.02)

Thanks for the feedback about appimage. I'll defer to your judgment on this issue.
