### ISSUE TITLE
docs should mention what Desktops rmw works with

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/rmw#253]
@elextr of the @Geany project was kind enough to take a look at the rmw web site and suggested that along with the distros mentioned, it should list the desktops that rmw works with.

The goal is [The FreeDesktop.org Trash specification](https://specifications.freedesktop.org/trash-spec/trashspec-latest.html), and I've tested rmw in the past with KDE, GNOME, and currently with XFCE (the desktop I use daily).

**Comment by Jammyjamjamman** [comment]
I'm not entirely sure what @elextr is exactly wanting. But, from what I can tell, this is solely a CLI project which is totally independent from whichever desktop you're using.... it doesn't even need a desktop environment! Debatably, that means you could say rmw is compatible with all desktops or no desktops.

Although freedesktop claims it's *`a project to work on interoperability and shared base technology for free software desktop environments for the X Window System on Linux and other Unix-like operating systems`*, it's actually covering an open specification for UNIX systems in general. The specification you linked is also covering plain terminal program specs, with or without X.

Desktop applications (I mean desktop, not "graphical" applications) are typically written in interpreted languages. I think KDE plasma uses python and Gnome 3 uses python and/ or Javascript. So, if we wanted to integrate rmw into desktop applications, we would first need an interface to higher level langs (like what SWIG implements).

**Comment by andy5995** [comment]
These are the first 2 lines of my config file

```
WASTE = $HOME/.trash.rmw
WASTE = $HOME/.local/share/Trash/
```

The 2nd line is for my "Desktop" trash, i.e. The files that I see when I open the trash on my XFCE Desktop. When I run purge, it will scan that as well as the first. Also, if I use `rmw -s` I can view the files that are in there, and optionally restore them.

That's about the extent of the desktop integration.

One way that rmw tries to conform to the FreeDesktop trash specification is "escaping" path names when removed (if appropriate), and  unescaping them when they are restored.

There's 3 functions involved with that.. here's 2 of them...

https://remove-to-waste.info/doxygen/html/trashinfo__rmw_8c.html#a7900e6a6777838e267f1ca2bb0dad310 

Historical trivia: Those functions were added in a patch @blah1898 did a couple years ago, and he in fact was the one who first told me about the specification. :)

Anyway.. I probably need to give some thought as to what needs to be said in the docs. As you point out, @Jammyjamjamman there's really not much real integration happening, but it probably merits some mention  and clarity, moreso for people who would want to use rmw for purging their desktop trash like I do.

**Comment by elextr** [comment]
@Jammyjamjamman the first line of the website says it sends files to _desktop_ trash, that implys to me that if I open my desktops file manager and click on the trash icon it will show files trashed by rmw.  

So I just pointed out that further down it lists _distros_ it has been tested with, but not which _desktops_ it has been tested with on those distros.  I'm a bit of a cynic about desktops complying with standards so I wouldn't take it for granted that they all work.

**Comment by andy5995** [comment]
> @Jammyjamjamman the first line of the website says it sends files to _desktop_ trash, that implys to me that if I open my desktops file manager and click on the trash icon it will show files trashed by rmw.

@elextr , you were right to infer that; I failed to mention above, it can do that, too.

However, in the [default config file](https://github.com/theimpossibleastronaut/rmw/blob/e2b15e72daf8dad780abde366fe4103a5a7feb21/rmwrc#L10), that's disabled. rmw doesn't try to automatically detect the path to the "desktop" trash, the user has to uncomment the line or enter it manually.

In this example, both these folders are on the same filesystem.

```
WASTE = $HOME/.trash.rmw
WASTE = $HOME/.local/share/Trash/
```

If I use `rmw foo`, then *foo* gets put in the first trash folder. But if I were to comment out the first line, *foo* would get sent to the second folder, and *foo* would be visible if I open my Trash folder from my desktop environment.

Alternatively, using `rmw -s` a user can see from the command line the contents of his desktop trash (provided the line is enabled in the config), and also restore them from the command line or from an ncurses interface.

But I'm really starting to see now that I need to review, update, and consolidate some of the docs regarding the behavior, how rmw works, and note that it hasn't been tested on **every** desktop environment, etc.

**Comment by Jammyjamjamman** [comment]
> @Jammyjamjamman the first line of the website says it sends files to _desktop_ trash, that implys to me that if I open my desktops file manager and click on the trash icon it will show files trashed by rmw.
> 
> So I just pointed out that further down it lists _distros_ it has been tested with, but not which _desktops_ it has been tested with on those distros. I'm a bit of a cynic about desktops complying with standards so I wouldn't take it for granted that they all work.

I see. I only brief-read website intro + didn't know what desktop compatibility` meant for this project, which is why I was confused.

I wonder which desktops are actually freedesktop compliant... "the good ones" xD

**Comment by andy5995** [comment]
> I wonder which desktops are actually freedesktop compliant... "the good ones" xD

In the "early days" of testing rmw, I tried on KDE and Gnome on Slackware, Debian, and probably some others, I don't remember. At the time, both those desktops used the ~/.local/share/Trash  folder and the same `.trashinfo` file format that rmw uses today.

I've been using Xfce for the last few years, and that's the same as well.

**Comment by andy5995** [comment]
Just tested with XFCE on OpenBSD 6.4; looks like another match.

**Comment by andy5995** [comment]
I've updated the program description and added info to the [faq on the website](https://remove-to-waste.info/faq.html)
