### ISSUE TITLE
compiling on arch linux failed

### ISSUE THREAD

**Issue by muralikodali** [theimpossibleastronaut/rmw#280]
compiling on arch linux failed with following errors :  

Making all in src
make[1]: Entering directory '/home/murali/Downloads/rmw/build/src'
make  all-am
make[2]: Entering directory '/home/murali/Downloads/rmw/build/src'
  CCLD     rmw
/bin/ld: rmw-restore_rmw.o:/home/murali/Downloads/rmw/build/src/../../src/rmw.h:95: multiple definition of `verbose'; rmw-main.o:/home/murali/Downloads/rmw/build/src/../../src/rmw.h:95: first defined here
/bin/ld: rmw-config_rmw.o:/home/murali/Downloads/rmw/build/src/../../src/rmw.h:95: multiple definition of `verbose'; rmw-main.o:/home/murali/Downloads/rmw/build/src/../../src/rmw.h:95: first defined here
/bin/ld: rmw-config_rmw.o:/home/murali/Downloads/rmw/build/src/../../src/main.h:35: multiple definition of `HOMEDIR'; rmw-main.o:/home/murali/Downloads/rmw/build/src/../../src/main.h:35: first defined here
/bin/ld: rmw-parse_cli_options.o:/home/murali/Downloads/rmw/build/src/../../src/rmw.h:95: multiple definition of `verbose'; rmw-main.o:/home/murali/Downloads/rmw/build/src/../../src/rmw.h:95: first defined here
/bin/ld: rmw-strings_rmw.o:/home/murali/Downloads/rmw/build/src/../../src/rmw.h:95: multiple definition of `verbose'; rmw-main.o:/home/murali/Downloads/rmw/build/src/../../src/rmw.h:95: first defined here
/bin/ld: rmw-purging_rmw.o:/home/murali/Downloads/rmw/build/src/../../src/rmw.h:95: multiple definition of `verbose'; rmw-main.o:/home/murali/Downloads/rmw/build/src/../../src/rmw.h:95: first defined here
/bin/ld: rmw-purging_rmw.o:/home/murali/Downloads/rmw/build/src/../../src/main.h:35: multiple definition of `HOMEDIR'; rmw-main.o:/home/murali/Downloads/rmw/build/src/../../src/main.h:35: first defined here
/bin/ld: rmw-messages_rmw.o:/home/murali/Downloads/rmw/build/src/../../src/rmw.h:95: multiple definition of `verbose'; rmw-main.o:/home/murali/Downloads/rmw/build/src/../../src/rmw.h:95: first defined here
/bin/ld: rmw-time_rmw.o:/home/murali/Downloads/rmw/build/src/../../src/rmw.h:95: multiple definition of `verbose'; rmw-main.o:/home/murali/Downloads/rmw/build/src/../../src/rmw.h:95: first defined here
/bin/ld: rmw-trashinfo_rmw.o:/home/murali/Downloads/rmw/build/src/../../src/rmw.h:95: multiple definition of `verbose'; rmw-main.o:/home/murali/Downloads/rmw/build/src/../../src/rmw.h:95: first defined here
/bin/ld: rmw-utils_rmw.o:/home/murali/Downloads/rmw/build/src/../../src/rmw.h:95: multiple definition of `verbose'; rmw-main.o:/home/murali/Downloads/rmw/build/src/../../src/rmw.h:95: first defined here
/bin/ld: rmw-bst.o:/home/murali/Downloads/rmw/build/src/../../src/rmw.h:95: multiple definition of `verbose'; rmw-main.o:/home/murali/Downloads/rmw/build/src/../../src/rmw.h:95: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:466: rmw] Error 1
make[2]: Leaving directory '/home/murali/Downloads/rmw/build/src'
make[1]: *** [Makefile:365: all] Error 2
make[1]: Leaving directory '/home/murali/Downloads/rmw/build/src'
make: *** [Makefile:452: all-recursive] Error 1

**Comment by andy5995** [comment]
Hi @muralikodali . Thanks for your interest in rmw.

Which version of arch and which version of rmw?

**Comment by muralikodali** [comment]
arch linux -  Linux 5.6.13-arch1-1
(archlinux-2020.05.01-x86_64)

i have cloned rmw with git, today.

**Comment by andy5995** [comment]
I have archlinux in a docker image. I haven't updated it in several months. I ran the image, and built rmw with no problems. Then I updated the arch image. After that, I got the same errors as @muralikodali 

Compiler: gcc (GCC) 10.1.0

This is the first time I tried building rmw with a gcc version higher than 9.

I have no idea how to fix or workaround this yet, or if it will fix itself with a different version of gcc 10.x.

**Comment by andy5995** [comment]
I created a [post on LQ](https://www.linuxquestions.org/questions/showthread.php?p=6124441#post6124441) for this issue.

**Comment by andy5995** [comment]
Fixed @muralikodali . Thank you for the report.

**Comment by muralikodali** [comment]
thanks.
compiled successfully on my machine.

**Comment by andy5995** [comment]
I appreciate you trying it out, @muralikodali.  Please let me know sometime how rmw works for you

**Comment by andy5995** [comment]
Hey @muralikodali , I published a new release yesterday with the gcc-10 fix included.
