### ISSUE TITLE
update German translation

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/rmw#353]
The Deutsche strings are a little out of date.

The instructions for working on translations are at https://remove-to-waste.info/translating.html

**Comment by astitva0011** [comment]
hello, i would like to work on this issue. 
could you assign this issue to me?

**Comment by andy5995** [comment]
Ok. See https://remove-to-waste.info/translating.html and let me know if you have any questions after reading that.

**Comment by m1ga** [comment]
it has some spelling mistakes in the current strings so make sure to not use Google Translate and correct the existing broken strings too :wink:

**Comment by andy5995** [comment]
> it has some spelling mistakes in the current strings so make sure to not use Google Translate and correct the existing broken strings too wink

@m1ga Thanks. Would you like to work on this?

**Comment by m1ga** [comment]
sure @andy5995, I can make a PR later today :+1:

**Comment by m1ga** [comment]
Quick question:

is https://github.com/theimpossibleastronaut/rmw/pull/356/files#diff-6686c8173bf4fa70e9c9755259206f2c5c4fa9fde6269d36e5262dcc09abcf25L190 and https://github.com/theimpossibleastronaut/rmw/pull/356/files#diff-6686c8173bf4fa70e9c9755259206f2c5c4fa9fde6269d36e5262dcc09abcf25R197 a string I need to translate or is it a `:error:` an ID I need to keep in English?

**Comment by andy5995** [comment]
@m1ga "warning" and "error" can both be translated.

**Comment by m1ga** [comment]
thanks, than it should be fine now
