### ISSUE TITLE
Update Dutch translation

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/rmw#362]
The Dutch strings are a little outdated. About 75% of them are completed.

For translation instructions, please see https://remove-to-waste.info/translating.html

@sexybiggetje wanna take a crack at this before I give the issue a hacktoberfest label?

**Comment by sexybiggetje** [comment]
I've sent some screenshots to your signal about something weird happening in transifex. It has a lot of '1%s' printed, on strings that were already translated before (and thus now differ). I've translated the 6 strings that didn't have issues.

**Comment by sexybiggetje** [comment]
I've updated the translations fully after learning that you replaced them with %s and I could disable the option to replace those in transifex :)

**Comment by andy5995** [comment]
> I've updated the translations fully after learning that you replaced them with %s and I could disable the option to replace those in transifex :)

Thanks

Do you have access to disable them? If not I should be able to give you access.
