### ISSUE TITLE
add feature to purge: purge by filespec

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/rmw#40]
```
<parthsuresh96> Got it..But what if someone wanted to purge a file from his system immediately ?
<parthsuresh96> A virus maybe :)
<andy5995> that's a good question
<andy5995> If a user thinks a file in the trash has a virus, he could delete it manually
<andy5995> rmw doesn't have an option to purge files using a file spec, but maybe that would be a good feature
<andy5995> and maybe 0 should be used for "empty all trash now"
<andy5995> and -1 used to disable purging
```

**Comment by andy5995** [comment]
I'm thinking that 0 should not change at this point - A value that suddenly changes from _completely disable_ tp _erase all_ may unpleasantly surprise someone.

As for an **empty all trash** feature, I thought using an environmental variable would be appropriate. The rmw command would need to be preceded by `RMWTRASH=empty`, combined with purge. That will empty all trash folders.

So although _confirmation_ wouldn't be required, there would have to be some extra thought involved, which should help those who would like more safety from a program that's main purpose is to provide safety.

1. Modify purge()
1. Use [getenv()](http://www.tutorialspoint.com/c_standard_library/c_function_getenv.htm) to check the env var
  * If the var doesn't exist, will it cause an error?

2. If it finds the env var, and if it's equal to  "clean", then have purge empty everything.
  * [L68](https://github.com/andy5995/rmw/blob/6897b17fa0b12d740c2bc3dca50a6c894ddfeddc/src/functions/purging_rmw.c#L368): adding `|| getenv("RMWTRASH") == "clean"`would probably be all that's needed.

**Comment by andy5995** [comment]
@parthsuresh Can I assign you this ticket?

**Comment by parthsuresh** [comment]
Yes @andy5995 I'd like to work on this.

**Comment by andy5995** [comment]
When I wrote this:
` || getenv("RMWTRASH") == "clean"`

I meant this:
`|| strcmp (getenv("RMWTRASH"), "clean")`

**Comment by parthsuresh** [comment]
Isn't it : 
`|| !strcmp (getenv("RMWTRASH"), "clean")`

strcmp returns zero if the two strings are equal

I've put in a pull-request.

**Comment by andy5995** [comment]
> Isn't it :
|| !strcmp (getenv("RMWTRASH"), "clean")

@parthsuresh Yes, thank you for the correction. :)

**Comment by andy5995** [comment]
I've changed the title of this issue; the RMWTRASH=empty feature was added last year.

The way I see adding a feature like purging by wildcard file specification is using `rmw --purge <optional filespec>`

Is anyone interested in working on this?

**Comment by andy5995** [comment]
I'll reopen this later depending on feature-demand.
