### ISSUE TITLE
Please consider adding autocompletion for fishshell

### ISSUE THREAD

**Issue by ccoVeille** [theimpossibleastronaut/rmw#436]
I worked on this based on your 0.9.2

https://gist.github.com/ccoVeille/b78a446dc5b65ed7db2150e30e9fc2f7

I don't know if you are interested in this.

But you may add it to something like `contrib/autocomplete/rmw.fish`

Thanks

**Comment by ccoVeille** [comment]
I'm not using zsh, but I can look for code completion if needed

**Comment by ccoVeille** [comment]
I might be at the wrong place in fact, I could open a ticket on https://github.com/fish-shell/fish-shell/

If found the PR about adding `trash-cli` tool on it https://github.com/fish-shell/fish-shell/pull/9560

Let me know if you are interested in providing the fish completion in your code repository, if not, leave a comment and close the ticket. Then I will open a PR on fish-shell repository.

**Comment by andy5995** [comment]
Yes, thank you. I could provide it in the rmw repository. Would you like to open a PR?

I don't really know anything this completion stuff, could you explain a little more? If it's in the rmw code repository, it's easy for other fish users to use it? Should it be installed to a specific location when rmw is installed?

**Comment by ccoVeille** [comment]
I will check other open source projects on the best way to add it to a project like yours.

Then I will happily open an PR.

**Comment by ccoVeille** [comment]
Based on the few research I made completions are often in a completion folder at root level

Like this
https://github.com/containers/podman/tree/main/completions

Or in etc folder

https://github.com/mislav/hub/tree/5c547ed804368763064e51f3990851e267e88edd/etc

Or a `contrib` or `utils`

I think I will use `completions` folder at root level if you agree

**Comment by andy5995** [comment]
That's sounds just fine. And ChatGPT seems to agree as well:

>For user-contributed fish shell completion files in your rmw project repository, you can create a dedicated directory to store these files. A common convention is to place shell completion scripts in a directory named completions or shell_completions.

```
rmw/
  ├── completions/
  │   ├── fish/
  │   │   └── rmw.fish
  │   └── ... (other shell completions)
  ├── src/
  ├── ...
```

**Comment by ccoVeille** [comment]
I think we are good now. What do you think ?

**Comment by ccoVeille** [comment]
Now, it was merged. I'm curious to see if once released, the rmw homebrew formula will package the fish completion automatically
