### ISSUE TITLE
tests fail after 2038

### ISSUE THREAD

**Issue by bmwiedemann** [theimpossibleastronaut/rmw#439]
While working on [reproducible builds](https://reproducible-builds.org/) for [openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds), I found that our `rmw-0.9.2` package fails to build after
2038-01-19T03:23:38 UTC
which is when 32-bit signed integer UNIX time values roll over.

```
Summary of Failures:

14/16 rmw / test_basic.sh             FAIL            0.02s   exit status 1
16/16 rmw / test_restore.sh           FAIL            0.05s   exit status 1
```

Background:
As part of my work on reproducible builds for openSUSE, I check that software still gives identical build results in the future.
The usual offset is +16 years, because that is how long I expect some software will be used in some places.
This showed up failing tests in our package build.
See https://reproducible-builds.org/ for why this matters.

[testlog.txt](https://github.com/theimpossibleastronaut/rmw/files/14738685/testlog.txt)

**Comment by andy5995** [comment]
Thanks for reporting @bmwiedemann . I'll need some time (no pun intended) to figure out a fix.

**Comment by andy5995** [comment]
I'm using [libfaketime](https://github.com/wolfcw/libfaketime) for testing.

(I first tried using a docker container but the system time on the host would change as well. Also I tried in a VirtualBox, but when I change the time, it syncs back to the original time a second or two later.)

Line 1103-1109 of testlog.txt shows part of the problem. The first 3 lines, where the paths are opened and closed with angle brackets, those three lines should not exist. I don't know why they are being output. In rmw and in the test scripts I do not have any commands to output those paths with angle brackets, or the paths without angle brackets.

Those are the paths from test/rmw.testrc which is a config file used in the test scripts. Why they are being output there I don't know yet.

I am able to reproduce this using libfaketime.

```
OUTPUT:
---
  [/home/abuild/rpmbuild/BUILD/rmw-0.9.2/x86_64-suse-linux/test/rmw-tests-home/test_restore.sh_dir/.Waste/files]
  [/home/abuild/rpmbuild/BUILD/rmw-0.9.2/x86_64-suse-linux/test/rmw-tests-home/test_restore.sh_dir/.local/share/Waste-2/files]
  [/home/abuild/rpmbuild/BUILD/rmw-0.9.2/x86_64-suse-linux/test/rmw-tests-home/test_restore.sh_dir/.local/share/Waste-3/files]
+'/home/abuild/rpmbuild/BUILD/rmw-0.9.2/x86_64-suse-linux/test/rmw-tests-home/test_restore.sh_dir/.Waste/files/read_only_file' -> '/home/abuild/rpmbuild/BUILD/rmw-0.9.2/x86_64-suse-linux/test/rmw-tests-home/test_restore.sh_dir/somefiles/read_only_file'
-/home/abuild/rpmbuild/BUILD/rmw-0.9.2/x86_64-suse-linux/test/rmw-tests-home/test_restore.sh_dir/.Waste/info/read_only_file.trashinfo
+'/home/abuild/rpmbuild/BUILD/rmw-0.9.2/x86_64-suse-linux/test/rmw-tests-home/test_restore.sh_dir/.Waste/files/topdir' -> '/home/abuild/rpmbuild/BUILD/rmw-0.9.2/x86_64-suse-linux/test/rmw-tests-home/test_restore.sh_dir/somefiles/topdir'
-/home/abuild/rpmbuild/BUILD/rmw-0.9.2/x86_64-suse-linux/test/rmw-tests-home/test_restore.sh_dir/.Waste/info/topdir.trashinfo
```

When I just run the test_restore.sh test:

    meson test test_restore.sh -v

The output for that section should be:

```
OUTPUT:
---
+'/home/andy/src/rmw-project/rmw/_build/test/rmw-tests-home/test_restore.sh_dir/.Waste/files/read_only_file' -> '/home/andy/
src/rmw-project/rmw/_build/test/rmw-tests-home/test_restore.sh_dir/somefiles/read_only_file'
-/home/andy/src/rmw-project/rmw/_build/test/rmw-tests-home/test_restore.sh_dir/.Waste/info/read_only_file.trashinfo
+'/home/andy/src/rmw-project/rmw/_build/test/rmw-tests-home/test_restore.sh_dir/.Waste/files/topdir' -> '/home/andy/src/rmw-
project/rmw/_build/test/rmw-tests-home/test_restore.sh_dir/somefiles/topdir'
-/home/andy/src/rmw-project/rmw/_build/test/rmw-tests-home/test_restore.sh_dir/.Waste/info/topdir.trashinfo
```

**Comment by bmwiedemann** [comment]
As an alternative to libfaketime, I use `qemu-kvm -rtc base=2038-11-11T11:11:11 ...`

**Comment by bmwiedemann** [comment]
The old code had
```C
    if ((st_time_var->now - atoi(time_prev)) < SECONDS_IN_A_DAY)
      return false;
```

and I think the trouble came from the `atoi` - did you try just change that one to `atoll` ?

**Comment by bmwiedemann** [comment]
I tested and submitted that surprisingly simple+straightforward fix.

**Comment by andy5995** [comment]
Well done, and thank you! I've added your patch from #444 to #442

**Comment by andy5995** [comment]
> The old code had
> 
> ```c
>     if ((st_time_var->now - atoi(time_prev)) < SECONDS_IN_A_DAY)
>       return false;
> ```
> 
> and I think the trouble came from the `atoi` - did you try just change that one to `atoll` ?

I first changed it to atol() but the two tests still failed on my 64-bit system. When I added [this else if](https://github.com/theimpossibleastronaut/rmw/blob/f5262a32b7ac3d2b16d4c0c69db3043a2afc87b0/src/purging_rmw.c#L68) the tests started working.
