### ISSUE TITLE
Add support for moving files between btrfs volumes and subvolumes

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/rmw#451]
### Discussed in https://github.com/theimpossibleastronaut/rmw/discussions/447

<div type='discussions-op-text'>

<sup>Originally posted by **luigir-it** March 26, 2024</sup>
Hi.
Today I did some changes on how I handle trash. I decided to create a `@Trash` subvolume and symlink `~/.local/share/Trash` to it.
There aren't any issue with Dolphin  (KDE gui file manager), everything works as before: I can trash files, folders, restore them... 

But the utility I was using before (`trash-cli`) stopped working. So I tried everything else I could find on the AUR, and none of them did work.
I came across rmw, and it looks simple and straightforward, but has the same issue: with `WASTE=$HOME/.local/share/Trash` in the config file,  deleting files yield this result: 
`
:error: while trying to move (rename)
  haha -> /home/luigi/.local/share/Trash/files/haha_195333-240326 -- remove_to_waste:L362
rename(): Invalid cross-device link
`

This `Invalid cross-device link` is the same output error of trash-cli and similar utilities. 

Is there a way to fix it? Like I said, Dolphin works fine with this new setup.</div>

**Comment by andy5995** [comment]
@luigir-it Me and @Jammyjamjamman started working on this in https://github.com/theimpossibleastronaut/rmw/pull/462

**Comment by andy5995** [comment]
@luigir-it If you're still interested in this feature, can you pull the changes in #462 and give it a try? It's not done yet, but you should be able to do `./rmw haha' with no errors (if I understand your setup correctly). rmw should move the file to your @Trash and create a trashinfo file.

**Comment by luigir-it** [comment]
Hi. It works but I found two (probably uncorrelated) issues.

1. WASTE must be set to `~/.local/share/@Trash` subvolume, not the `~/.local/share/Trash` symlink, otherwise I get
```
:error: while trying to move (rename)
  7hh22 -> /home/pcino/.local/share/Trash/files/7hh22 -- remove_to_waste:L387
rename(): Invalid cross-device link
```

2. Weird behavior when deleting a file in the upper directory (screenshot for convenience)
![the file is removed but not present in the Trash](https://github.com/user-attachments/assets/b5f3bf63-3303-4265-9b06-96b9c1b1e4c4)
The file is still being trashed, but not corresponding trashinfo file is not created (meaning that, for example, Dolphin will not list it in the Trash directory)

**Comment by andy5995** [comment]
@luigir-it I've made some improvements and pushed the changes.

I did more testing locally. I have two separate btrfs partitions. I have a WASTE subvolume on one partition and a symlink to it. Things seems to work as expected now. Could you please pull changes and test again? No rush... I still need to review error-checking and some of the control flow to account for potential paranormal activity.

**Comment by luigir-it** [comment]
With latest changes (up to "Fix build on Mac and BSD")
- n.1 is solved
- n.2 isn't.

**Comment by andy5995** [comment]
@luigir-it Please paste in your ~/.config/rmwrc file, and tell me which waste folder that '../ask2224' file should be going to. Is that on your btrfs partition?

Could you also try that same command (rmw ../ask2224) with rmw 0.9.2 (the latest release) to see if you get the same result?

**Comment by andy5995** [comment]
@luigir-it I'm now able to reproduce the same error. I'll investigate and create a fix.

**Comment by andy5995** [comment]
I believe it's fixed now. Could you give it another try, @luigir-it ?

**Comment by luigir-it** [comment]
Yup it does work :)

**Comment by andy5995** [comment]
>     2. Weird behavior when deleting a file in the upper directory (screenshot for convenience)
>        ![the file is removed but not present in the Trash](https://private-user-images.githubusercontent.com/64033455/380450090-b5f3bf63-3303-4265-9b06-96b9c1b1e4c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3ODgxMDEsIm5iZiI6MTczMDc4NzgwMSwicGF0aCI6Ii82NDAzMzQ1NS8zODA0NTAwOTAtYjVmM2JmNjMtMzMwMy00MjY1LTliMDYtOTZiOWMxYjFlNGM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA2MjMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNjg0NjRlOGI1MmYwYzYwMGM2NDQ4YzU3MGY0YTY2YmM0MTk0ZjUzNTY5NGQ3Y2E2ZTNkODc1ZmIzOTFhYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9s572WCWOI0HKH0VorbUOtmTMQv_88GDsPvQHdKdRHU)
>        The file is still being trashed, but not corresponding trashinfo file is not created (meaning that, for example, Dolphin will not list it in the Trash directory)

The error is back. I added one last test before release (https://github.com/theimpossibleastronaut/rmw/commit/a8596ff15a80e76b1a13c01c4c9b52cf7def5d0b) and it magically reappeared.

**Comment by andy5995** [comment]
The test passes locally but fails in the CI.

**Comment by luigir-it** [comment]
Hi Andy. Unfortunately I no longer use my laptop, so I cannot test further. I could try this weekend but cannot assure it.

**Comment by andy5995** [comment]
Oh, thank you very much for the offer, but I have enough here to test it. I've narrowed down the problem so probably will have a fix by the end of tomorrow.

**Comment by luigir-it** [comment]
Hi Andy. I just looked at the test
While I'm not an expert by any means, the test probably fails [here](https://github.com/theimpossibleastronaut/rmw/blob/a8596ff15a80e76b1a13c01c4c9b52cf7def5d0b/test/test_btrfs_clone.sh#L48) because of a typo

**Comment by andy5995** [comment]
lol... I was really hungry when I added that test. :)

The problem isn't related to btrfs so I'm gonna close this...

**Comment by andy5995** [comment]
> The problem isn't related to btrfs so I'm gonna close this...

https://github.com/theimpossibleastronaut/rmw/issues/473
