### ISSUE TITLE
Test on OpenSuse Tumbleweed

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/rmw#470]
I'd like to add a test to the CI for OpenSuse Tumbleweed. Basically a 'build_env' Dockerfile needs to be made like the two in https://github.com/theimpossibleastronaut/rmw/tree/master/docker and then add it to the matrix in https://github.com/theimpossibleastronaut/rmw/blob/master/.github/workflows/c-cpp.yml

Note I don't plan to use the entrypoint test script anymore https://github.com/theimpossibleastronaut/rmw/issues/469

@ehbello Is this something you'd be interested in?

**Comment by ehbello** [comment]
> @ehbello Is this something you'd be interested in?

Nope, I don't use rmw at all, except to contribute to your gh-action-build-deb fork and even less with OpenSuse, sorry.
