### ISSUE TITLE
Running and building rmw on Windows

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/rmw#71]
Using [CygWin](https://cygwin.com/), I built a Windows binary for rmw. It's available in the win32 on the develop branch.

Instead of HOME, it uses the environmental variable LOCALAPPDATA.

Anyone wanting to experiment with it can find their LOCALAPPDATA directory by using the `set` command. On Windows, `rmw` should create a trash folder there (.trash/rmw/files & .trash/rmw/info), and create a configuration directory in %LOCALAPPDATA%
1. copy rmwrc to %LOCALAPPDATA%\rmw and rename it to config
2. Place rmw.exe and cygwin1.dll somewhere in your path

Problems I've had so far:
1. Doesn't create the .trash/info dir until the second time it's run.
2. When I restored a file after using rmw, it sent it to the correct path, but it used the cygwin path of `/cygdrive/c...`

If you try building from source, you'll need to `#define WIN32` in the CFLAGS option, or at the top of rmw.h.

I'm not writing out complete instructions yet until I've tested it more and added a bit more code to ensure portability. Nothing is in place yet for `make install`.

Anyone wishing to help me get that code in place or test, please let me know.

**Comment by andy5995** [comment]
If anyone is interested in doing this, do you think using Cygwin is the best method? I'm open to other ideas.

**Comment by sexybiggetje** [comment]
AFAIK, for a native executable Cygwin is the easiest and best method. I dislike the extra dll, but it's already in my "unixutils" folder anyway.

Nowadays however you have a full linux system running if you want with WSL. Basically what WINE does for Windows on Linux, WSL does for Linux on Windows. Best thing of all, it's just an optional install. WSL compiles a working Linux binary.

**Comment by andy5995** [comment]
>AFAIK, for a native executable Cygwin is the easiest and best method.

I agree. I have very little experience with Windows programming, but from what I do know, Cygwin is the way to go.

I'm glad I documented some of my experience with building and running it on Windows in the first post. That was over a year ago.

I have no plans to do anything with this, but if anyone has some experience with Windows programming and wants to implement this, please do so. :)

**Comment by andy5995** [comment]
Regarding getting the right path or HOME info, this might give some clues when we work on this in the future:

https://github.com/MegaGlest/megaglest-source/blob/12998eb10f6447ac89a45d1e6d76f17946647b7a/source/shared_lib/sources/util/properties.cpp#L214-L265

**Comment by andy5995** [comment]
I'll let a regular Windows developer decide on the best way to do this. My only requirement is that it use the existing build system GNU autotools.

**Comment by andy5995** [comment]
> I'll let a regular Windows developer decide on the best way to do this. My only requirement is that it use the existing build system GNU autotools.

I think I could be open to a different build system for Windows. Again.. I'd leave that to the developer to decide.

**Comment by andy5995** [comment]
Starting to add a cmake build system in https://github.com/theimpossibleastronaut/rmw/pull/288.

**Comment by andy5995** [comment]
> Starting to add a cmake build system in #288.

I don't have the patience for it. Closing that draft.

**Comment by andy5995** [comment]
There are existing Windows utilities.
