### ISSUE TITLE
Note to those with collaborator access

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/rmw#84]
It's best to make changes on separate branches and make a PR.

You are welcome to use your collaborator access for assigning tickets to yourself, or creating labels for issues if you would like.

I don't have a stated policy on this yet and need to update the docs. The problem is... I don't get auto-notified of direct pushes. PR's make things easier for me to review and manage. Thanks!

Please remember to "star" this project (upper right corner) and [join the chat room](https://join.slack.com/t/removetowaste/shared_invite/enQtMjU3NTA0NTI2OTgzLTkzMzQxNDhjYzlkM2UxMTA2MzJjNWYyZjAyYzkyNWNmZjJmYWZmYjUyODk2NzNkNzBhMzFjOGZkMTg2MzAxMTM) if you like.

The [Contributing wiki page](https://github.com/andy5995/rmw/wiki/Contributing) contains important information about making pull requests.

**Comment by rlyshw** [comment]
I was having weird issues when I tried to PR from my separate fork, where it didn't match the HEAD of the fork to the HEAD of the main repo, so I used a branch on this repo. Let me know if that was bad practice.

Also, FYI, I'm sure you can set the master branch to "protected" or at least restrict the branch access of the collaborators. This way you'll avoid the devastating effects of a `push -u force`.

**Comment by andy5995** [comment]
>Also, FYI, I'm sure you can set the master branch to "protected" or at least restrict the branch access of the collaborators. This way you'll avoid the devastating effects of a push -u force.

Thanks @rlyshw I was wondering about an option like that! 

>I was having weird issues when I tried to PR from my separate fork, where it didn't match the HEAD of the fork to the HEAD of the main repo, so I used a branch on this repo. Let me know if that was bad practice.

>I was having weird issues when I tried to PR from my separate fork, where it didn't match the HEAD of the fork to the HEAD of the main repo, so I used a branch on this repo. Let me know if that was bad practice.

I don't know if that's bad practice, but I'll tell you how you should be able to sync your fork up so that doesn't happen again.

Switch to the master branch of your fork. Assuming you have no changes or edits on it that you want to save:
`git reset --hard fce389fe2bb11c54851b00ba20d4279c6f7c15af` that will set your HEAD back to an earlier commit.

Assuming there are no errors: `git push`

If that doesn't work, `git push -f`  **(normally you wouldn't need -f)**

Now [sync with the upstream](https://github.com/andy5995/rmw/wiki/Contributing#syncing)

That should prevent problems with future patches.

If you're working on a patch and on a different branch, to merge in the latest changes from master:

`git rebase master`

It's not always necessary to rebase. I believe after you rebase, you'd need ` -f` to push the changes.

i.e. if you've pushed an issue_81 branch to your fork, and later on you've rebased, you'd need to use -f.

I'm not a git expert, so there may be other ways to do some of this, but hopefully it's a good guide that will help in the future.

**Comment by rlyshw** [comment]
That is a nice guide, worth adding to the contribution wiki page.
